### ISSUE TITLE
Still up to date?

### ISSUE THREAD

**Issue by Ninu-Nightwatch** [simkli/SimklThemeSettingExport#3]
As the last contribution is from 2016, I wanted to ask, if usage with Shopware 5.4. is still recommended?

Kinde regards, Amitab

**Comment by simkli** [comment]
Hi Amitab,
I used it in Shopware 5.3.
It would be much appreciated if you could test it yourself and report here.
Thanks!

**Comment by Ninu-Nightwatch** [comment]
Ok, thank you!
It will take a few weeks, till I will start testing it.
I will let you know the results.

**Comment by simkli** [comment]
I just tested it in 5.4.5. and it worked.
